### ISSUE TITLE
Combinatorics Stars & Bars Intro 

### ISSUE THREAD

**Issue by RexMortem** [DesyncTheThird/DesyncTheThird.github.io#2]
The combinations from rolling 10 D6 dice should be:

(10 + (6-1))!/(10! * (6-1)!) = (10 + 5)!/(10! * 5!) = 15!/(10! * 5!) = 3003. (not 5005)

(Page 190; not the Stars & Bars section)

**Comment by DesyncTheThird** [comment]
tyty; forgot to subtract 1 from 6 in the choose function
